Repository AY2324S1-CS2113-F11-3/tp, pull requests merged in 2023-11, with the labels that each got.

#65 Save Flsahcard id
  data/flashcards/flashcard.txt
  src/main/java/seedu/duke/flashcard/Flashcard.java
  src/main/java/seedu/duke/flashcard/FlashcardStorage.java
  src/main/java/seedu/duke/flashcard/FlashcardStorageParser.java
Labels: priority.Medium

#69 Add FindEvent & DeleteAll
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/calendar/CalendarCommandParser.java
  src/main/java/seedu/duke/calendar/EventList.java
  src/main/java/seedu/duke/calendar/command/AddEventCommand.java
  src/main/java/seedu/duke/calendar/command/DeleteAllEvents.java
  src/main/java/seedu/duke/calendar/command/FindEvent.java
  src/main/java/seedu/duke/flashcard/FlashcardCommandParser.java
Labels: type.Story, priority.High

#71 Fix Command Formatting
  data/events/event.txt
  data/flashcards/flashcard 18.50.11.txt
  flashcard.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/calendar/EventList.java
  src/main/java/seedu/duke/calendar/EventStorage.java
  src/main/java/seedu/duke/calendar/command/AddEventCommand.java
  src/main/java/seedu/duke/calendar/command/DeleteAllEvents.java
  src/main/java/seedu/duke/calendar/command/DeleteEventCommand.java
  src/main/java/seedu/duke/calendar/command/FindEvent.java
  src/main/java/seedu/duke/calendar/command/ListCalendarEventsCommand.java
Labels: priority.High, severity.Low

#73 Resolve Data dir error and disable INFO logs
  data/events/event.txt
  src/main/java/seedu/duke/calendar/EventDirectory.java
  src/main/java/seedu/duke/calendar/EventStorage.java
  src/main/java/seedu/duke/flashcard/FlashcardDirectory.java
  src/main/java/seedu/duke/flashcard/FlashcardStorage.java
Labels: priority.Medium

#81 Add FlashcardStorage puml image
  docs/photo/FlashcardStorage-0.png
Labels: priority.Low

#116 Fix Delete Event Bug
  data/events/event.txt
  src/main/java/seedu/duke/calendar/CalendarCommandParser.java
  src/main/java/seedu/duke/calendar/EventList.java
  src/main/java/seedu/duke/calendar/command/AddEventCommand.java
  src/main/java/seedu/duke/calendar/command/DeleteEventCommand.java
  src/main/java/seedu/duke/calendar/command/DualEventCommand.java
  src/main/java/seedu/duke/calendar/command/ListCalendarEventsCommand.java
Labels: severity.Low

#135 Add exception for file changes in flashcard.txt
  data/flashcards/flashcard.txt
  data/flashcards/flashcard1110.txt
  src/main/java/seedu/duke/calendar/CalendarManager.java
  src/main/java/seedu/duke/flashcard/Flashcard.java
  src/main/java/seedu/duke/flashcard/FlashcardComponent.java
  src/main/java/seedu/duke/storage/EventStorage.java
  src/main/java/seedu/duke/storage/EventStorageParser.java
  src/main/java/seedu/duke/storage/FlashcardStorage.java
  src/main/java/seedu/duke/storage/FlashcardStorageParser.java
  src/main/java/seedu/duke/storage/exceptions/EventFileFormatException.java
  src/main/java/seedu/duke/storage/exceptions/FlashcardFileFormatException.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.Medium

#137 Add exception for file changes in event.txt
  src/main/java/seedu/duke/storage/EventStorage.java
  src/main/java/seedu/duke/storage/EventStorageParser.java
  src/main/java/seedu/duke/storage/FlashcardStorageParser.java
Labels: priority.Medium

#151 Add some Javadoc
  src/main/java/seedu/duke/storage/exceptions/EventFileFormatException.java
  src/main/java/seedu/duke/storage/exceptions/FlashcardFileFormatException.java
Labels: priority.Low
