Repository AY2324S1-CS2113-F11-3/tp, pull requests merged in 2023-10, with the labels that each got.

#22 Implement Calendar Command
  src/main/java/seedu/duke/calendar/Calendar.java
  src/main/java/seedu/duke/calendar/CalendarCommandParser.java
  src/main/java/seedu/duke/calendar/Event.java
  src/main/java/seedu/duke/calendar/EventList.java
  src/main/java/seedu/duke/calendar/command/AddEventCommand.java
  src/main/java/seedu/duke/calendar/command/DeleteEventCommand.java
  src/main/java/seedu/duke/calendar/command/EventCommand.java
  src/main/java/seedu/duke/calendar/command/ListCalendarEventsCommand.java
  src/main/java/seedu/duke/calendar/command/UnknownCommand.java
Labels: type.Story, priority.High

#25 Fix CodingStyle
  src/main/java/seedu/duke/calendar/EventList.java
  src/main/java/seedu/duke/calendar/command/AddEventCommand.java
  src/main/java/seedu/duke/calendar/command/DeleteEventCommand.java
  src/main/java/seedu/duke/calendar/command/EventCommand.java
  src/main/java/seedu/duke/calendar/command/ListCalendarEventsCommand.java
Labels: type.Story, priority.High, priority.Medium

#27 Connect Calendar with Duke
  data/flashcard.txt
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/calendar/Calendar.java
  src/main/java/seedu/duke/calendar/CalendarCommandParser.java
  src/main/java/seedu/duke/calendar/CalendarManager.java
  src/main/java/seedu/duke/calendar/command/EventCommand.java
Labels: type.Story, priority.High

#40 Assertions problem resolving
  src/main/java/seedu/duke/flashcard/FlashcardStorage.java
  text-ui-test/ACTUAL.TXT
Labels: priority.Low

#62 Update DG: Add Information for Calendar
  data/events/event.txt
  data/flashcards/flashcard.txt
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Duke.java
Labels: type.Task, priority.Medium
